public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        byte cat = 10;
        System.out.println("Значение переменной cat с типом byte равно " + cat);
        short dog = 25252;
        System.out.println("Значение переменной dog с типом short равно " + dog);
        int fish = 1000000;
        System.out.println("Значение переменной fish с типом int = " + fish);
        long frog = 1_234_567_890L;
        System.out.println("Значение переменной frog с типом long = " + frog);
        float ship = 5.75f;
        System.out.println("Значение переменной ship с типом float = " + ship);
        double twins = 5.75;
        System.out.println("Значение переменной twins с типом double = " + twins);
        char letter = 928;
        System.out.println("Значение переменной letter с типом char = " + letter);
        boolean question = 5 <= 2;
        System.out.println("Значение переменной question с типом boolean = " + question);
        System.out.println();
        System.out.println("Задача 2");
        double tomato = 27.12;
        long apple = 987678965549L;
        float pear = 2.786f;
        boolean pepper = false;
        char potato = 569;
        short cucumber = -159;
        int pumpkin = 27897;
        byte melon = 67;
        System.out.println(tomato + "\n" + apple + "\n" + pear + "\n" + pepper + "\n" + potato + "\n" + cucumber + "\n" + pumpkin + "\n" + melon);
        System.out.println();
        System.out.println("Задача 3");
        int studentsLP = 23;
        int studentsAS = 27;
        int studentsEA = 30;
        int studentsAll = studentsLP + studentsAS + studentsEA;
        int allPapers = 480;
        int paperPerStudent = allPapers / studentsAll;
        System.out.println("На каждого ученика рассчитано " + paperPerStudent + " листов бумаги");
        System.out.println();
        System.out.println("Задача 4");
        int bottlesPer2Min = 16;
        int bottlesPerMin = bottlesPer2Min / 2;
        int bottlesPer20Min = bottlesPerMin * 20;
        System.out.println("За 20 минут машина произвела бутылок " + bottlesPer20Min + " штук");
        int minutesInDay = 24 * 60;
        int bottlesPerDay = bottlesPerMin * minutesInDay;
        System.out.println("За 1 сутки машина произвела бутылок " + bottlesPerDay + " штук");
        int bottlesPer3Days = bottlesPerDay * 3;
        System.out.println("За три дня машина произвела бутылок " + bottlesPer3Days + " штук");
        int bottlesPerMonth = bottlesPerDay * 30;
        System.out.println("За средний календарный месяц машина произвела бутылок " + bottlesPerMonth + " штук");
        System.out.println();
        System.out.println("Задача 5");
        int cansTotal = 120;
        int whitePer1Room = 2;
        int brownPer1Room = 4;
        int cansPer1Room = whitePer1Room + brownPer1Room;
        int roomsAmount = cansTotal / cansPer1Room;
        int whiteTotal = whitePer1Room * roomsAmount;
        int brownTotal = brownPer1Room * roomsAmount;
        System.out.println("В школе, где " + roomsAmount + " классов, нужно " + whiteTotal + " банок белой краски и " + brownTotal + " банок коричневой краски");
        System.out.println();
        System.out.println("Задача 6");
        int banana = 80 * 5;
        int milk = 105 * 2;
        int iceCream = 100 * 2;
        int eggs = 70 * 4;
        int breakfastWeight = banana + milk + iceCream + eggs;
        double bfWeightKilo = breakfastWeight * 0.001;
        System.out.println("Вес спорт-завтрака составляет " + breakfastWeight + " гр или " + bfWeightKilo + " кг" );
        System.out.println();
        System.out.println("Задача 7");
        double weightToLose = 7000;
        double grPerDay1 = 250;
        double amountOfDays1 = weightToLose / grPerDay1;
        double grPerDay2 = 500;
        double amountOfDays2 = weightToLose / grPerDay2;
        double averageAmountOfDays = (amountOfDays1 + amountOfDays2) / 2;//проверить! ответ верный, но я не уверена в способе его получения:)
        System.out.println("Если спортсмен будет терять по 250 гр, то на похудение уйдёт " + amountOfDays1 + " дней");
        System.out.println("Если спортсмен будет терять по 500 гр, то на похудение уйдёт " + amountOfDays2 + " дней");
        System.out.println("В среднем на похудение уйдёт " + averageAmountOfDays + " дней");
        System.out.println();
        System.out.println("Задача 8");
        int mashaSalary = 67760;
        int denisSalary = 83690;
        int krisSalary = 76230;
        double mashaSalaryNew = mashaSalary + (mashaSalary * 0.1);
        double denisSalaryNew = denisSalary + (denisSalary * 0.1);
        double krisSalaryNew = krisSalary + (krisSalary * 0.1);
        double mashaSalaryDifference = (mashaSalaryNew * 12) - (mashaSalary * 12);
        double denisSalaryDifference = (denisSalaryNew * 12) - (denisSalary * 12);
        double krisSalaryDifference = (krisSalaryNew * 12) - (krisSalary * 12);
        System.out.println("Теперь Маша получает " + mashaSalaryNew + " рублей. Годовой доход вырос на " + mashaSalaryDifference + " рублей");
        System.out.println("Теперь Денис получает " + denisSalaryNew + " рублей. Годовой доход вырос на " + denisSalaryDifference + " рублей");
        System.out.println("Теперь Кристина получает " + krisSalaryNew + " рублей. Годовой доход вырос на " + krisSalaryDifference + " рублей");
    }
}